import { describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";

/** RMD-08 开始时从 root-source-owner audit 导出的精确迁移清单。 */
const RMD_08_MOVES = [
  ["web/components/MetaAgentPanel.tsx", "apps/web/components/MetaAgentPanel.tsx"],
  ["web/components/ai-elements/chat-message-content.css", "apps/web/components/ai-elements/chat-message-content.css"],
  ["web/components/ai-elements/code-block.tsx", "apps/web/components/ai-elements/code-block.tsx"],
  ["web/components/ai-elements/conversation.tsx", "apps/web/components/ai-elements/conversation.tsx"],
  ["web/components/ai-elements/iframe-preview.tsx", "apps/web/components/ai-elements/iframe-preview.tsx"],
  ["web/components/ai-elements/index.ts", "apps/web/components/ai-elements/index.ts"],
  ["web/components/ai-elements/message-attachments.tsx", "apps/web/components/ai-elements/message-attachments.tsx"],
  ["web/components/ai-elements/message.tsx", "apps/web/components/ai-elements/message.tsx"],
  ["web/components/ai-elements/permission-request.tsx", "apps/web/components/ai-elements/permission-request.tsx"],
  ["web/components/ai-elements/prompt-input.tsx", "apps/web/components/ai-elements/prompt-input.tsx"],
  ["web/components/ai-elements/reasoning.tsx", "apps/web/components/ai-elements/reasoning.tsx"],
  ["web/components/ai-elements/shimmer.tsx", "apps/web/components/ai-elements/shimmer.tsx"],
  ["web/components/ai-elements/tool.tsx", "apps/web/components/ai-elements/tool.tsx"],
  ["web/components/config/BatchActionBar.tsx", "apps/web/components/config/BatchActionBar.tsx"],
  ["web/components/config/ConfirmDialog.tsx", "apps/web/components/config/ConfirmDialog.tsx"],
  ["web/components/config/DataTable.tsx", "apps/web/components/config/DataTable.tsx"],
  ["web/components/config/EmptyState.tsx", "apps/web/components/config/EmptyState.tsx"],
  ["web/components/config/FormDialog.tsx", "apps/web/components/config/FormDialog.tsx"],
  ["web/components/config/StatusBadge.tsx", "apps/web/components/config/StatusBadge.tsx"],
  ["web/components/config/index.ts", "apps/web/components/config/index.ts"],
  ["web/src/App.tsx", "apps/web/src/App.tsx"],
  ["web/src/__tests__/agent-create-enter-flow.test.ts", "apps/web/src/__tests__/agent-create-enter-flow.test.ts"],
  [
    "web/src/__tests__/agent-form-dialog-bulk-pure-options.test.ts",
    "apps/web/src/__tests__/agent-form-dialog-bulk-pure-options.test.ts",
  ],
  [
    "web/src/__tests__/agent-form-dialog-editor-guards.test.ts",
    "apps/web/src/__tests__/agent-form-dialog-editor-guards.test.ts",
  ],
  [
    "web/src/__tests__/agent-form-dialog-high-gap-conversions.test.tsx",
    "apps/web/src/__tests__/agent-form-dialog-high-gap-conversions.test.tsx",
  ],
  [
    "web/src/__tests__/agent-form-dialog-options-boundaries.test.tsx",
    "apps/web/src/__tests__/agent-form-dialog-options-boundaries.test.tsx",
  ],
  [
    "web/src/__tests__/agent-form-dialog-pure-logic.test.ts",
    "apps/web/src/__tests__/agent-form-dialog-pure-logic.test.ts",
  ],
  [
    "web/src/__tests__/agent-form-dialog-round54-pure.test.ts",
    "apps/web/src/__tests__/agent-form-dialog-round54-pure.test.ts",
  ],
  ["web/src/__tests__/agent-form-dialog-ssr.test.tsx", "apps/web/src/__tests__/agent-form-dialog-ssr.test.tsx"],
  ["web/src/__tests__/agent-home-generation.test.tsx", "apps/web/src/__tests__/agent-home-generation.test.tsx"],
  ["web/src/__tests__/agent-node-selector.test.ts", "apps/web/src/__tests__/agent-node-selector.test.ts"],
  [
    "web/src/__tests__/agent-resource-picker-interaction.test.tsx",
    "apps/web/src/__tests__/agent-resource-picker-interaction.test.tsx",
  ],
  [
    "web/src/__tests__/agent-sidebar-instance-order.test.ts",
    "apps/web/src/__tests__/agent-sidebar-instance-order.test.ts",
  ],
  ["web/src/__tests__/agent-utils.test.ts", "apps/web/src/__tests__/agent-utils.test.ts"],
  ["web/src/__tests__/api-client.test.ts", "apps/web/src/__tests__/api-client.test.ts"],
  ["web/src/__tests__/api-result-utils.test.ts", "apps/web/src/__tests__/api-result-utils.test.ts"],
  ["web/src/__tests__/artifacts-preview-events.test.ts", "apps/web/src/__tests__/artifacts-preview-events.test.ts"],
  ["web/src/__tests__/auth-preference.test.ts", "apps/web/src/__tests__/auth-preference.test.ts"],
  ["web/src/__tests__/config-datatable.test.ts", "apps/web/src/__tests__/config-datatable.test.ts"],
  ["web/src/__tests__/config-helpers.test.ts", "apps/web/src/__tests__/config-helpers.test.ts"],
  ["web/src/__tests__/config-routing.test.ts", "apps/web/src/__tests__/config-routing.test.ts"],
  ["web/src/__tests__/config-types.test.ts", "apps/web/src/__tests__/config-types.test.ts"],
  ["web/src/__tests__/confirm-dialog.test.tsx", "apps/web/src/__tests__/confirm-dialog.test.tsx"],
  ["web/src/__tests__/context-queue.test.ts", "apps/web/src/__tests__/context-queue.test.ts"],
  ["web/src/__tests__/dark-mode-components.test.tsx", "apps/web/src/__tests__/dark-mode-components.test.tsx"],
  ["web/src/__tests__/data-table-round41-pure.test.tsx", "apps/web/src/__tests__/data-table-round41-pure.test.tsx"],
  ["web/src/__tests__/data-table-ssr.test.tsx", "apps/web/src/__tests__/data-table-ssr.test.tsx"],
  ["web/src/__tests__/date-picker.test.tsx", "apps/web/src/__tests__/date-picker.test.tsx"],
  [
    "web/src/__tests__/extract-changed-files-boundaries.test.ts",
    "apps/web/src/__tests__/extract-changed-files-boundaries.test.ts",
  ],
  ["web/src/__tests__/extract-changed-files.test.ts", "apps/web/src/__tests__/extract-changed-files.test.ts"],
  ["web/src/__tests__/folder-upload-batching.test.ts", "apps/web/src/__tests__/folder-upload-batching.test.ts"],
  ["web/src/__tests__/form-utils.test.ts", "apps/web/src/__tests__/form-utils.test.ts"],
  ["web/src/__tests__/fs-upload-url.test.ts", "apps/web/src/__tests__/fs-upload-url.test.ts"],
  ["web/src/__tests__/instances-api.test.ts", "apps/web/src/__tests__/instances-api.test.ts"],
  ["web/src/__tests__/message-additional-ssr.test.tsx", "apps/web/src/__tests__/message-additional-ssr.test.tsx"],
  ["web/src/__tests__/narrators-i18n.test.ts", "apps/web/src/__tests__/narrators-i18n.test.ts"],
  ["web/src/__tests__/new-session-dialog-form.test.ts", "apps/web/src/__tests__/new-session-dialog-form.test.ts"],
  ["web/src/__tests__/pagination.test.tsx", "apps/web/src/__tests__/pagination.test.tsx"],
  [
    "web/src/__tests__/params-editor-round42-pure.test.tsx",
    "apps/web/src/__tests__/params-editor-round42-pure.test.tsx",
  ],
  ["web/src/__tests__/peri-task-details-api.test.ts", "apps/web/src/__tests__/peri-task-details-api.test.ts"],
  ["web/src/__tests__/permission-options.test.ts", "apps/web/src/__tests__/permission-options.test.ts"],
  ["web/src/__tests__/preview-utils-normalize.test.ts", "apps/web/src/__tests__/preview-utils-normalize.test.ts"],
  [
    "web/src/__tests__/pure-logic-transform-boundaries.test.ts",
    "apps/web/src/__tests__/pure-logic-transform-boundaries.test.ts",
  ],
  ["web/src/__tests__/random-uuid-polyfill.test.ts", "apps/web/src/__tests__/random-uuid-polyfill.test.ts"],
  ["web/src/__tests__/retry.test.ts", "apps/web/src/__tests__/retry.test.ts"],
  ["web/src/__tests__/strip-html-tags.test.ts", "apps/web/src/__tests__/strip-html-tags.test.ts"],
  [
    "web/src/__tests__/structured-thread-additional.test.ts",
    "apps/web/src/__tests__/structured-thread-additional.test.ts",
  ],
  [
    "web/src/__tests__/structured-thread-boundaries.test.ts",
    "apps/web/src/__tests__/structured-thread-boundaries.test.ts",
  ],
  ["web/src/__tests__/system-sandbox.test.ts", "apps/web/src/__tests__/system-sandbox.test.ts"],
  ["web/src/__tests__/task-form-schema.test.ts", "apps/web/src/__tests__/task-form-schema.test.ts"],
  ["web/src/__tests__/todo.test.ts", "apps/web/src/__tests__/todo.test.ts"],
  ["web/src/__tests__/tree-component.test.tsx", "apps/web/src/__tests__/tree-component.test.tsx"],
  ["web/src/__tests__/use-task-views.test.tsx", "apps/web/src/__tests__/use-task-views.test.tsx"],
  ["web/src/__tests__/utils.test.ts", "apps/web/src/__tests__/utils.test.ts"],
  ["web/src/api/fs.ts", "apps/web/src/api/fs.ts"],
  ["web/src/api/instances.ts", "apps/web/src/api/instances.ts"],
  ["web/src/api/peri-task-details.ts", "apps/web/src/api/peri-task-details.ts"],
  ["web/src/api/registry.ts", "apps/web/src/api/registry.ts"],
  ["web/src/components/FilePickerDialog.tsx", "apps/web/src/components/FilePickerDialog.tsx"],
  ["web/src/components/OrgSwitcher.tsx", "apps/web/src/components/OrgSwitcher.tsx"],
  ["web/src/components/PermissionTab.tsx", "apps/web/src/components/PermissionTab.tsx"],
  [
    "web/src/components/agent-panel/ChangedFilesSection.tsx",
    "apps/web/src/components/agent-panel/ChangedFilesSection.tsx",
  ],
  ["web/src/components/agent-panel/FileTabsBar.tsx", "apps/web/src/components/agent-panel/FileTabsBar.tsx"],
  [
    "web/src/components/agent-panel/FileTreeContextMenu.tsx",
    "apps/web/src/components/agent-panel/FileTreeContextMenu.tsx",
  ],
  ["web/src/components/agent-panel/FileTreeTab.tsx", "apps/web/src/components/agent-panel/FileTreeTab.tsx"],
  ["web/src/components/agent-panel/PreviewTab.tsx", "apps/web/src/components/agent-panel/PreviewTab.tsx"],
  ["web/src/components/agent-panel/TopModeTabs.tsx", "apps/web/src/components/agent-panel/TopModeTabs.tsx"],
  ["web/src/components/agent-panel/WorkbenchPanel.tsx", "apps/web/src/components/agent-panel/WorkbenchPanel.tsx"],
  ["web/src/components/agent-panel/artifacts-dialogs.tsx", "apps/web/src/components/agent-panel/artifacts-dialogs.tsx"],
  [
    "web/src/components/agent-panel/artifacts-files-workspace.tsx",
    "apps/web/src/components/agent-panel/artifacts-files-workspace.tsx",
  ],
  [
    "web/src/components/agent-panel/file-tree-input-dialog.tsx",
    "apps/web/src/components/agent-panel/file-tree-input-dialog.tsx",
  ],
  ["web/src/components/agent-panel/file-tree-model.ts", "apps/web/src/components/agent-panel/file-tree-model.ts"],
  ["web/src/components/agent-panel/file-tree-view.tsx", "apps/web/src/components/agent-panel/file-tree-view.tsx"],
  [
    "web/src/components/agent-panel/preview/FileViewerPreview.tsx",
    "apps/web/src/components/agent-panel/preview/FileViewerPreview.tsx",
  ],
  [
    "web/src/components/agent-panel/preview/html-plugin.ts",
    "apps/web/src/components/agent-panel/preview/html-plugin.ts",
  ],
  [
    "web/src/components/agent-panel/preview/native-pdf-plugin.ts",
    "apps/web/src/components/agent-panel/preview/native-pdf-plugin.ts",
  ],
  ["web/src/components/agent-panel/preview/overrides.css", "apps/web/src/components/agent-panel/preview/overrides.css"],
  ["web/src/components/agent-panel/preview/utils.ts", "apps/web/src/components/agent-panel/preview/utils.ts"],
  [
    "web/src/components/agent-panel/use-file-tree-events.ts",
    "apps/web/src/components/agent-panel/use-file-tree-events.ts",
  ],
  ["web/src/components/agent-panel/use-file-uploads.ts", "apps/web/src/components/agent-panel/use-file-uploads.ts"],
  ["web/src/components/file-icon-helper.tsx", "apps/web/src/components/file-icon-helper.tsx"],
  ["web/src/components/layout/app-header.tsx", "apps/web/src/components/layout/app-header.tsx"],
  ["web/src/components/layout/app-page.tsx", "apps/web/src/components/layout/app-page.tsx"],
  ["web/src/hooks/use-changed-files-stats.ts", "packages/web-runtime/web/hooks/use-changed-files-stats.ts"],
  ["web/src/hooks/use-task-views.ts", "apps/web/src/hooks/use-task-views.ts"],
  ["web/src/hooks/useMetaAgent.ts", "apps/web/src/hooks/useMetaAgent.ts"],
  ["web/src/hooks/usePageVisible.ts", "packages/web-runtime/web/hooks/use-page-visible.ts"],
  ["web/src/i18n/locales/en/agentHome.json", "apps/web/src/i18n/locales/en/agentHome.json"],
  ["web/src/i18n/locales/en/agentPanel.json", "apps/web/src/i18n/locales/en/agentPanel.json"],
  ["web/src/i18n/locales/en/agents.json", "apps/web/src/i18n/locales/en/agents.json"],
  ["web/src/i18n/locales/en/common.json", "apps/web/src/i18n/locales/en/common.json"],
  ["web/src/i18n/locales/en/components.json", "apps/web/src/i18n/locales/en/components.json"],
  ["web/src/i18n/locales/en/dashboard.json", "apps/web/src/i18n/locales/en/dashboard.json"],
  ["web/src/i18n/locales/en/environments.json", "apps/web/src/i18n/locales/en/environments.json"],
  ["web/src/i18n/locales/en/login.json", "apps/web/src/i18n/locales/en/login.json"],
  ["web/src/i18n/locales/en/models.json", "apps/web/src/i18n/locales/en/models.json"],
  ["web/src/i18n/locales/en/sessions.json", "apps/web/src/i18n/locales/en/sessions.json"],
  ["web/src/i18n/locales/en/settings.json", "apps/web/src/i18n/locales/en/settings.json"],
  ["web/src/i18n/locales/en/sidebar.json", "apps/web/src/i18n/locales/en/sidebar.json"],
  ["web/src/i18n/locales/en/tasks.json", "apps/web/src/i18n/locales/en/tasks.json"],
  ["web/src/i18n/locales/en/toolNarrator.json", "apps/web/src/i18n/locales/en/toolNarrator.json"],
  ["web/src/i18n/locales/zh/agentHome.json", "apps/web/src/i18n/locales/zh/agentHome.json"],
  ["web/src/i18n/locales/zh/agentPanel.json", "apps/web/src/i18n/locales/zh/agentPanel.json"],
  ["web/src/i18n/locales/zh/agents.json", "apps/web/src/i18n/locales/zh/agents.json"],
  ["web/src/i18n/locales/zh/common.json", "apps/web/src/i18n/locales/zh/common.json"],
  ["web/src/i18n/locales/zh/components.json", "apps/web/src/i18n/locales/zh/components.json"],
  ["web/src/i18n/locales/zh/dashboard.json", "apps/web/src/i18n/locales/zh/dashboard.json"],
  ["web/src/i18n/locales/zh/environments.json", "apps/web/src/i18n/locales/zh/environments.json"],
  ["web/src/i18n/locales/zh/login.json", "apps/web/src/i18n/locales/zh/login.json"],
  ["web/src/i18n/locales/zh/models.json", "apps/web/src/i18n/locales/zh/models.json"],
  ["web/src/i18n/locales/zh/sessions.json", "apps/web/src/i18n/locales/zh/sessions.json"],
  ["web/src/i18n/locales/zh/settings.json", "apps/web/src/i18n/locales/zh/settings.json"],
  ["web/src/i18n/locales/zh/sidebar.json", "apps/web/src/i18n/locales/zh/sidebar.json"],
  ["web/src/i18n/locales/zh/tasks.json", "apps/web/src/i18n/locales/zh/tasks.json"],
  ["web/src/i18n/locales/zh/toolNarrator.json", "apps/web/src/i18n/locales/zh/toolNarrator.json"],
  ["web/src/lib/admin-key.ts", "apps/web/src/lib/admin-key.ts"],
  ["web/src/lib/agent-node.ts", "apps/web/src/lib/agent-node.ts"],
  ["web/src/lib/agent-resource-access.ts", "apps/web/src/lib/agent-resource-access.ts"],
  ["web/src/lib/agent-utils.ts", "apps/web/src/lib/agent-utils.ts"],
  ["web/src/lib/api-result.ts", "apps/web/src/lib/api-result.ts"],
  ["web/src/lib/artifacts-preview-events.ts", "packages/web-runtime/web/lib/artifacts-preview-events.ts"],
  ["web/src/lib/auth-preference.ts", "apps/web/src/lib/auth-preference.ts"],
  ["web/src/lib/chat-stats.ts", "packages/web-runtime/web/lib/chat-stats.ts"],
  ["web/src/lib/citation-preview-context.tsx", "apps/web/src/lib/citation-preview-context.tsx"],
  ["web/src/lib/config-events.ts", "packages/web-runtime/web/lib/config-events.ts"],
  ["web/src/lib/context-queue.ts", "apps/web/src/lib/context-queue.ts"],
  ["web/src/lib/extract-changed-files.ts", "apps/web/src/lib/extract-changed-files.ts"],
  ["web/src/lib/form-utils.ts", "apps/web/src/lib/form-utils.ts"],
  ["web/src/lib/password-crypto.ts", "apps/web/src/lib/password-crypto.ts"],
  ["web/src/lib/retry.ts", "apps/web/src/lib/retry.ts"],
  ["web/src/lib/strip-html-tags.ts", "apps/web/src/lib/strip-html-tags.ts"],
  ["web/src/lib/structured-to-thread.ts", "packages/web-runtime/web/chat/structured-to-thread.ts"],
  ["web/src/lib/todo.ts", "packages/web-runtime/web/chat/todo.ts"],
  ["web/src/lib/token-stats.ts", "apps/web/src/lib/token-stats.ts"],
  ["web/src/lib/tool-semantic.ts", "apps/web/src/lib/tool-semantic.ts"],
  ["web/src/lib/types.ts", "apps/web/src/lib/types.ts"],
  ["web/src/lib/use-context-queue.ts", "apps/web/src/lib/use-context-queue.ts"],
  ["web/src/lib/use-workflow-events.ts", "apps/web/src/lib/use-workflow-events.ts"],
  ["web/src/pages/LoginPage.tsx", "apps/web/src/pages/LoginPage.tsx"],
  ["web/src/pages/agent-panel/AgentAppShell.tsx", "apps/web/src/pages/agent-panel/AgentAppShell.tsx"],
  ["web/src/pages/agent-panel/AgentPanelLayout.tsx", "apps/web/src/pages/agent-panel/AgentPanelLayout.tsx"],
  ["web/src/pages/agent-panel/AgentPanelPage.tsx", "apps/web/src/pages/agent-panel/AgentPanelPage.tsx"],
  ["web/src/pages/agent-panel/AgentSidebar.tsx", "apps/web/src/pages/agent-panel/AgentSidebar.tsx"],
  ["web/src/pages/agent-panel/AgentSidebarConfig.tsx", "apps/web/src/pages/agent-panel/AgentSidebarConfig.tsx"],
  ["web/src/pages/agent-panel/AgentSidebarTree.tsx", "apps/web/src/pages/agent-panel/AgentSidebarTree.tsx"],
  ["web/src/pages/agent-panel/ArtifactsPanel.tsx", "apps/web/src/pages/agent-panel/ArtifactsPanel.tsx"],
  ["web/src/pages/agent-panel/agent-create-navigation.ts", "apps/web/src/pages/agent-panel/agent-create-navigation.ts"],
  ["web/src/pages/agent-panel/agent-panel.css", "apps/web/src/pages/agent-panel/agent-panel.css"],
  ["web/src/pages/agent-panel/artifacts-workspace.css", "apps/web/src/pages/agent-panel/artifacts-workspace.css"],
  [
    "web/src/pages/agent-panel/components/KnowledgeGraphPanel.tsx",
    "apps/web/src/pages/agent-panel/components/KnowledgeGraphPanel.tsx",
  ],
  [
    "web/src/pages/agent-panel/pages/AgentDashboardPage.tsx",
    "apps/web/src/pages/agent-panel/pages/AgentDashboardPage.tsx",
  ],
  ["web/src/pages/agent-panel/pages/AgentHomePage.tsx", "apps/web/src/pages/agent-panel/pages/AgentHomePage.tsx"],
  [
    "web/src/pages/agent-panel/pages/AgentManagementPage.tsx",
    "apps/web/src/pages/agent-panel/pages/AgentManagementPage.tsx",
  ],
  ["web/src/pages/agent-panel/shared/AgentCardList.tsx", "apps/web/src/pages/agent-panel/shared/AgentCardList.tsx"],
  [
    "web/src/pages/agent-panel/shared/agent-master-detail-workspace.tsx",
    "apps/web/src/pages/agent-panel/shared/agent-master-detail-workspace.tsx",
  ],
  ["web/src/types/config.ts", "apps/web/src/types/config.ts"],
  ["web/src/types/cytoscape-fcose.d.ts", "apps/web/src/types/cytoscape-fcose.d.ts"],
  ["web/src/types/global.d.ts", "apps/web/src/types/global.d.ts"],
  ["web/src/types/index.ts", "apps/web/src/types/index.ts"],
  ["web/src/types/react-file-icon.d.ts", "apps/web/src/types/react-file-icon.d.ts"],
  ["web/src/vite-env.d.ts", "apps/web/src/vite-env.d.ts"],
  ["web/tsconfig.json", "apps/web/tsconfig.json"],
] as const;

describe("RMD-08 apps/web migration", () => {
  // 182 个保留的应用壳源文件都必须从旧根路径移除，并存在于唯一的规范目标。
  // target 是「当前规范位置」而非恒定的 apps/web 路径：文件被后续迁移（如 C1 迁出
  // 宿主通用 web 运行时到 packages/web-runtime）再次搬走时同步改写 target，
  // 这样本守卫继续同时断言「旧根路径没有复活」与「规范位置确实存在」。
  test("removes every legacy source and retains its exact canonical target", () => {
    expect(RMD_08_MOVES).toHaveLength(182);
    for (const [source, target] of RMD_08_MOVES) {
      expect(existsSync(source), `legacy source still exists: ${source}`).toBe(false);
      expect(existsSync(target), `canonical target is missing: ${target}`).toBe(true);
    }
  });

  // 已批准退役的污染测试在旧根路径和迁移目标中都不得复活。
  test("keeps the retired card renderer test deleted", () => {
    expect(existsSync("web/src/__tests__/card-renderer-pure-utils.test.ts")).toBe(false);
    expect(existsSync("apps/web/src/__tests__/card-renderer-pure-utils.test.ts")).toBe(false);
  });
});
