import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import * as barrel from "../index";

const PKG_ROOT = join(import.meta.dir, "..", "..");
const packageExports = (
  JSON.parse(readFileSync(join(PKG_ROOT, "package.json"), "utf8")) as {
    exports: Record<string, string | { default?: string; types?: string }>;
  }
).exports;

/**
 * barrel 冒烟测试：只断言公共出口的名称与非空性，不渲染组件、不 mock 模块、不做 UI 结构断言。
 *
 * 期望清单按 `web/` 下的分组划分：`components` / `config` / `layout` / `lib` / `ui` 对应同名目录，
 * `barrel` 分组收纳「未被上述分组覆盖」的根 barrel 出口（原 ai-elements 基元与 chat 组各层模块）。
 * 清单刻意保持显式：模块被删除、导出被改名、barrel 少写一行 `export *`，都会在这里以具体名字失败，
 * 而不是等消费方运行时才发现。仅类型导出（TreeNodeData、DataTableProps、TagRendererConfig 等）在
 * 运行时不可见，由 `tsc` 的编译期检查覆盖，故不列在此处。
 *
 * 维护约定：`web/index.ts` 增删模块或改变导出名时必须同步本清单；末条数量断言用于发现「清单未同步」，
 * 逐名断言则负责发现「导出变少」，两者互补。清单按 ASCII 序排列（大写在前），便于用排序快速核对差异。
 */
const EXPECTED_EXPORTS: Record<string, readonly string[]> = {
  barrel: [
    "ACPMain",
    "AgentAvatar",
    "AgentBadge",
    "AgentBadgeSkeleton",
    "AssistantBubble",
    "CARD_STYLES",
    "ChatComposer",
    "ChatHeader",
    "ChatInteractionRegion",
    "ChatInteractionStack",
    "ChatInterface",
    "ChatQuoteMessage",
    "ChatSelectionAction",
    "ChatStatusPanel",
    "ChatView",
    "CitationLink",
    "CodeBlock",
    "CodeBlockCopyButton",
    "CommandMenu",
    "ComposerAssets",
    "ComposerContextMeter",
    "ComposerToolbar",
    "Conversation",
    "ConversationContent",
    "ConversationEmptyState",
    "ConversationScrollButton",
    "ConversationScrollButtons",
    "ConversationScrollToLastUserMessageButton",
    "FilePickerPanel",
    "FileTreeArborist",
    "FileTreeContextMenu",
    "FileTreeView",
    "HindsightToolCard",
    "IMAGE_COMPRESSION_OPTIONS",
    "IframePreview",
    "LAST_USER_MESSAGE_ATTR",
    "MAX_QUOTED_TEXT_LENGTH",
    "MAX_QUOTE_CONTEXT_PAYLOAD_LENGTH",
    "MAX_QUOTE_COUNT",
    "MAX_TOTAL_QUOTED_TEXT_LENGTH",
    "Message",
    "MessageAction",
    "MessageActions",
    "MessageAttachment",
    "MessageAttachments",
    "MessageBranch",
    "MessageBranchContent",
    "MessageBranchNext",
    "MessageBranchPage",
    "MessageBranchPrevious",
    "MessageBranchSelector",
    "MessageContent",
    "MessageResponse",
    "MessageToolbar",
    "PermissionPanel",
    "PromptInput",
    "PromptInputActionAddAttachments",
    "PromptInputActionMenu",
    "PromptInputActionMenuContent",
    "PromptInputActionMenuItem",
    "PromptInputActionMenuTrigger",
    "PromptInputAttachment",
    "PromptInputAttachments",
    "PromptInputBody",
    "PromptInputButton",
    "PromptInputCommand",
    "PromptInputCommandEmpty",
    "PromptInputCommandGroup",
    "PromptInputCommandInput",
    "PromptInputCommandItem",
    "PromptInputCommandList",
    "PromptInputCommandSeparator",
    "PromptInputFooter",
    "PromptInputHeader",
    "PromptInputHoverCard",
    "PromptInputHoverCardContent",
    "PromptInputHoverCardTrigger",
    "PromptInputProvider",
    "PromptInputSelect",
    "PromptInputSelectContent",
    "PromptInputSelectItem",
    "PromptInputSelectTrigger",
    "PromptInputSelectValue",
    "PromptInputSpeechButton",
    "PromptInputSubmit",
    "PromptInputTab",
    "PromptInputTabBody",
    "PromptInputTabItem",
    "PromptInputTabLabel",
    "PromptInputTabsList",
    "PromptInputTextarea",
    "PromptInputTools",
    "PromptJumpRail",
    "PublicErrorCard",
    "QuestionPanel",
    "Reasoning",
    "ReasoningContent",
    "ReasoningTrigger",
    "SessionModeSelector",
    "SessionSelectFallbackProvider",
    "Shimmer",
    "SidebarSessionList",
    "SubAgentPanel",
    "SubAgentToolCallGroupContext",
    "SystemMessage",
    "TodoChanges",
    "Tool",
    "ToolCallGroup",
    "ToolCallRow",
    "ToolContent",
    "ToolHeader",
    "ToolInput",
    "ToolJsonBlock",
    "ToolOutput",
    "ToolPermissionButtons",
    "UserBubble",
    "blobToBase64",
    "buildChatRenderBlocks",
    "buildChatRenderItems",
    "buildPromptText",
    "canDeleteSession",
    "cardKindToStyle",
    "classifyToolSemantic",
    "computeStats",
    "createQuotePreview",
    "derivePendingPermissions",
    "deriveTodoItems",
    "extractChangedFiles",
    "fileNameFromPath",
    "formatOutput",
    "formatTokenCount",
    "getChatUploadPath",
    "groupByRecency",
    "isHindsightTool",
    "isVisibleContentBlock",
    "kindLabel",
    "limitQuotedText",
    "narrate",
    "normalizeToolName",
    "parseChatQuotes",
    "prepareImageContent",
    "processImageFiles",
    "semanticToToolCardKind",
    "serializeChatQuotes",
    "simplifyModelDisplayName",
    "simplifyToolName",
    "splitFileReferences",
    "splitSystemReminderBlocks",
    "stripHtmlTags",
    "supportsFilePreview",
    "truncate",
    "uploadComposerFiles",
    "useComposerExternalInput",
    "useComposerHandlers",
    "useComposerState",
    "useDragUpload",
    "usePromptInputAttachments",
    "usePromptInputController",
    "useProviderAttachments",
    "useReasoning",
    "useSemiControlledState",
  ],
  components: [
    "AgentCardList",
    "AgentMasterDetailHeader",
    "AgentMasterDetailWorkspace",
    "FileTreeInputDialog",
    "FileTypeIcon",
    "FileViewerPreview",
    "PreviewTab",
    "WorkbenchPanel",
    "classifyFile",
    "getFileExtension",
    "getPreviewMimeType",
    "htmlPreviewPlugin",
    "loadByteAccuratePreviewSource",
    "nativePdfPlugin",
    "shouldLoadPreviewAsBlob",
  ],
  config: [
    "BatchActionBar",
    "ConfirmDialog",
    "DataTable",
    "EmptyState",
    "FormDialog",
    "ScopeFilterBar",
    "StatusBadge",
    "buildInitialExpandedState",
    "filterData",
    "getStatusTone",
    "paginateData",
    "sortData",
  ],
  layout: ["AppHeader", "AppPage"],
  lib: [
    "CardEventEmitter",
    "MessageEmitterContext",
    "ThemeProvider",
    "UI_COMPONENTS_NS",
    "cn",
    "copyTextToClipboard",
    "getRegisteredAllowedTags",
    "getRegisteredComponents",
    "getRegisteredTags",
    "getTagRenderer",
    "registerTagRenderer",
    "useCardEmit",
    "useTheme",
  ],
  ui: [
    "Accordion",
    "AccordionContent",
    "AccordionItem",
    "AccordionTrigger",
    "AlertDialog",
    "AlertDialogAction",
    "AlertDialogCancel",
    "AlertDialogContent",
    "AlertDialogDescription",
    "AlertDialogFooter",
    "AlertDialogHeader",
    "AlertDialogMedia",
    "AlertDialogOverlay",
    "AlertDialogPortal",
    "AlertDialogTitle",
    "AlertDialogTrigger",
    "Badge",
    "Button",
    "ButtonGroup",
    "ButtonGroupSeparator",
    "ButtonGroupText",
    "Calendar",
    "CalendarDayButton",
    "Card",
    "CardAction",
    "CardContent",
    "CardDescription",
    "CardFooter",
    "CardHeader",
    "CardTitle",
    "ChartContainer",
    "Checkbox",
    "Collapsible",
    "CollapsibleContent",
    "CollapsibleTrigger",
    "Command",
    "CommandDialog",
    "CommandEmpty",
    "CommandGroup",
    "CommandInput",
    "CommandItem",
    "CommandList",
    "CommandSeparator",
    "CommandShortcut",
    "ConnectionStatusBar",
    "DatePicker",
    "Dialog",
    "DialogClose",
    "DialogContent",
    "DialogDescription",
    "DialogFooter",
    "DialogHeader",
    "DialogOverlay",
    "DialogPortal",
    "DialogTitle",
    "DialogTrigger",
    "DropdownMenu",
    "DropdownMenuCheckboxItem",
    "DropdownMenuContent",
    "DropdownMenuGroup",
    "DropdownMenuItem",
    "DropdownMenuLabel",
    "DropdownMenuPortal",
    "DropdownMenuRadioGroup",
    "DropdownMenuRadioItem",
    "DropdownMenuSeparator",
    "DropdownMenuShortcut",
    "DropdownMenuSub",
    "DropdownMenuSubContent",
    "DropdownMenuSubTrigger",
    "DropdownMenuTrigger",
    "Form",
    "FormControl",
    "FormDescription",
    "FormField",
    "FormItem",
    "FormLabel",
    "FormMessage",
    "HoverCard",
    "HoverCardContent",
    "HoverCardTrigger",
    "Input",
    "InputGroup",
    "InputGroupAddon",
    "InputGroupButton",
    "InputGroupInput",
    "InputGroupText",
    "InputGroupTextarea",
    "Label",
    "Pagination",
    "Popover",
    "PopoverAnchor",
    "PopoverContent",
    "PopoverTrigger",
    "Progress",
    "ResizableHandle",
    "ResizablePanel",
    "ResizablePanelGroup",
    "ScrollArea",
    "ScrollBar",
    "Select",
    "SelectContent",
    "SelectGroup",
    "SelectItem",
    "SelectLabel",
    "SelectScrollDownButton",
    "SelectScrollUpButton",
    "SelectSeparator",
    "SelectTrigger",
    "SelectValue",
    "Separator",
    "Sheet",
    "SheetClose",
    "SheetContent",
    "SheetDescription",
    "SheetFooter",
    "SheetHeader",
    "SheetTitle",
    "SheetTrigger",
    "Skeleton",
    "Slider",
    "Spinner",
    "StatusDot",
    "StatusIndicator",
    "Switch",
    "Table",
    "TableBody",
    "TableCaption",
    "TableCell",
    "TableFooter",
    "TableHead",
    "TableHeader",
    "TableRow",
    "Tabs",
    "TabsContent",
    "TabsList",
    "TabsTrigger",
    "Textarea",
    "ThemeToggle",
    "Tooltip",
    "TooltipContent",
    "TooltipProvider",
    "TooltipTrigger",
    "Tree",
    "TreeItem",
    "TreeItemContent",
    "TreeItemGroup",
    "badgeVariants",
    "buttonGroupVariants",
    "buttonVariants",
    "collectDirectoryPaths",
    "filterFileTree",
    "findFileNode",
    "getConnectionStateLabel",
    "parsePathsToTree",
    "splitFileTreeSections",
    "tabsListVariants",
    "toTreeNodeData",
    "useFormField",
    "useRovingListNavigation",
  ],
};

describe("barrel 导出契约", () => {
  for (const [group, names] of Object.entries(EXPECTED_EXPORTS)) {
    test(`${group} 分组的导出都能从 barrel 取到`, () => {
      for (const name of names) {
        expect(Object.hasOwn(barrel, name), `${group} 分组缺少导出：${name}`).toBe(true);
      }
    });
  }

  test("barrel 的运行时导出均非空", () => {
    for (const [name, value] of Object.entries(barrel)) {
      expect(value, `${name} 的导出值为 null`).not.toBeNull();
      expect(value, `${name} 的导出值为 undefined`).not.toBeUndefined();
      if (typeof value === "string") {
        expect(value.length, `${name} 的导出值为空字符串`).toBeGreaterThan(0);
      }
    }
  });

  test("barrel 的运行时导出总数与期望清单一致", () => {
    const expectedTotal = Object.values(EXPECTED_EXPORTS).reduce((sum, names) => sum + names.length, 0);
    expect(Object.keys(barrel).length, "导出数量已变化，请同步 EXPECTED_EXPORTS").toBe(expectedTotal);
  });

  // barrel 公开的每个模块都必须有对应的 `exports` 深链键。只有 `export *` 是可深链的公开面：
  // 缺键时消费方只能经整包 barrel 取用（把整套组件图拉进自己的模块图），或退化为 `@/…` 相对路径穿越，
  // 后者正是 `web-package-not-to-app` 台账的来源。分组自身子 barrel（`./chat/narrators/index`）以
  // 目录名为键（`./chat/narrators`），与包 `exports` 的既有命名一致。
  test("barrel 公开的每个模块都有对应的 exports 深链键", () => {
    const barrelSource = readFileSync(join(import.meta.dir, "..", "index.ts"), "utf8");
    const targets = [
      ...new Set(
        [...barrelSource.matchAll(/^export [^;]*from "\.\/(.+?)";$/gm)].map((match) =>
          match[1].replace(/\/index$/, ""),
        ),
      ),
    ];
    // 扫描有效性自检：正则失配（改了 export 写法）时下面会「零缺口」地假通过。
    expect(targets.length).toBeGreaterThanOrEqual(120);
    const missing = targets.filter((target) => !Object.hasOwn(packageExports, `./${target}`));
    expect(missing, "barrel 已公开但 exports 缺少深链键").toEqual([]);
  });

  // 反向：`exports` 的每个子路径键都必须落在真实文件上。悬空键（改名后漏删、手写笔误）会让消费方
  // 在解析期报错，而 `tsc` 只检查仓库内已被引用的键，未被引用的悬空键不会被任何现有检查发现。
  test("exports 的子路径键都解析到真实文件", () => {
    const dangling = Object.entries(packageExports)
      .filter(([key]) => key !== "." && key !== "./styles.css")
      .flatMap(([key, value]) => {
        const target =
          typeof value === "string" ? value : ((value as { default?: string; types?: string }).default ?? "");
        return target && existsSync(join(PKG_ROOT, target)) ? [] : [`${key} -> ${target || "(无 default/types)"}`];
      });
    expect(dangling, "exports 存在悬空键").toEqual([]);
  });
});
