import { describe, expect, test } from "bun:test";
import * as barrel from "../index";

/**
 * barrel 冒烟测试：只断言公共出口的名称与非空性，不渲染组件、不 mock 模块、不做 UI 结构断言。
 *
 * 期望清单按 `web/index.ts` 的分组逐条列出，刻意保持显式：模块被删除、导出被改名、barrel 少写一行
 * `export *`，都会在这里以具体名字失败，而不是等消费方运行时才发现。仅类型导出（TreeNodeData、
 * DataTableProps、TagRendererConfig 等）在运行时不可见，由 `tsc` 的编译期检查覆盖，故不列在此处。
 *
 * 维护约定：`web/index.ts` 增删模块或改变导出名时必须同步本清单；末条数量断言用于发现「清单未同步」，
 * 逐名断言则负责发现「导出变少」，两者互补。
 */
const EXPECTED_EXPORTS: Record<string, readonly string[]> = {
  "ai-elements": [
    "CodeBlock",
    "CodeBlockCopyButton",
    "Conversation",
    "ConversationContent",
    "ConversationEmptyState",
    "ConversationScrollButton",
    "ConversationScrollButtons",
    "ConversationScrollToLastUserMessageButton",
    "IframePreview",
    "LAST_USER_MESSAGE_ATTR",
    "Message",
    "MessageAction",
    "MessageActions",
    "MessageAttachment",
    "MessageAttachments",
    "MessageBranch",
    "MessageBranchContent",
    "MessageBranchNext",
    "MessageBranchPage",
    "MessageBranchPrevious",
    "MessageBranchSelector",
    "MessageContent",
    "MessageResponse",
    "MessageToolbar",
    "PromptInput",
    "PromptInputActionAddAttachments",
    "PromptInputActionMenu",
    "PromptInputActionMenuContent",
    "PromptInputActionMenuItem",
    "PromptInputActionMenuTrigger",
    "PromptInputAttachment",
    "PromptInputAttachments",
    "PromptInputBody",
    "PromptInputButton",
    "PromptInputCommand",
    "PromptInputCommandEmpty",
    "PromptInputCommandGroup",
    "PromptInputCommandInput",
    "PromptInputCommandItem",
    "PromptInputCommandList",
    "PromptInputCommandSeparator",
    "PromptInputFooter",
    "PromptInputHeader",
    "PromptInputHoverCard",
    "PromptInputHoverCardContent",
    "PromptInputHoverCardTrigger",
    "PromptInputProvider",
    "PromptInputSelect",
    "PromptInputSelectContent",
    "PromptInputSelectItem",
    "PromptInputSelectTrigger",
    "PromptInputSelectValue",
    "PromptInputSpeechButton",
    "PromptInputSubmit",
    "PromptInputTab",
    "PromptInputTabBody",
    "PromptInputTabItem",
    "PromptInputTabLabel",
    "PromptInputTabsList",
    "PromptInputTextarea",
    "PromptInputTools",
    "Reasoning",
    "ReasoningContent",
    "ReasoningTrigger",
    "Shimmer",
    "Tool",
    "ToolContent",
    "ToolHeader",
    "ToolInput",
    "ToolOutput",
    "ToolPermissionButtons",
    "usePromptInputAttachments",
    "usePromptInputController",
    "useProviderAttachments",
    "useReasoning",
  ],
  components: [
    "AgentCardList",
    "AgentMasterDetailHeader",
    "AgentMasterDetailWorkspace",
    "FileTreeInputDialog",
    "FileTypeIcon",
    "WorkbenchPanel",
    "getFileExtension",
  ],
  config: [
    "BatchActionBar",
    "ConfirmDialog",
    "DataTable",
    "EmptyState",
    "FormDialog",
    "StatusBadge",
    "buildInitialExpandedState",
    "filterData",
    "getBadgeVariant",
    "paginateData",
    "sortData",
  ],
  layout: ["AppHeader", "AppPage"],
  lib: [
    "ThemeProvider",
    "UI_COMPONENTS_NS",
    "cn",
    "getRegisteredAllowedTags",
    "getRegisteredComponents",
    "getRegisteredTags",
    "getTagRenderer",
    "registerTagRenderer",
    "useTheme",
  ],
  ui: [
    "Accordion",
    "AccordionContent",
    "AccordionItem",
    "AccordionTrigger",
    "AlertDialog",
    "AlertDialogAction",
    "AlertDialogCancel",
    "AlertDialogContent",
    "AlertDialogDescription",
    "AlertDialogFooter",
    "AlertDialogHeader",
    "AlertDialogMedia",
    "AlertDialogOverlay",
    "AlertDialogPortal",
    "AlertDialogTitle",
    "AlertDialogTrigger",
    "Badge",
    "Button",
    "ButtonGroup",
    "ButtonGroupSeparator",
    "ButtonGroupText",
    "Calendar",
    "CalendarDayButton",
    "Card",
    "CardAction",
    "CardContent",
    "CardDescription",
    "CardFooter",
    "CardHeader",
    "CardTitle",
    "ChartContainer",
    "Checkbox",
    "Collapsible",
    "CollapsibleContent",
    "CollapsibleTrigger",
    "Command",
    "CommandDialog",
    "CommandEmpty",
    "CommandGroup",
    "CommandInput",
    "CommandItem",
    "CommandList",
    "CommandSeparator",
    "CommandShortcut",
    "ConnectionStatusBar",
    "DatePicker",
    "Dialog",
    "DialogClose",
    "DialogContent",
    "DialogDescription",
    "DialogFooter",
    "DialogHeader",
    "DialogOverlay",
    "DialogPortal",
    "DialogTitle",
    "DialogTrigger",
    "DropdownMenu",
    "DropdownMenuCheckboxItem",
    "DropdownMenuContent",
    "DropdownMenuGroup",
    "DropdownMenuItem",
    "DropdownMenuLabel",
    "DropdownMenuPortal",
    "DropdownMenuRadioGroup",
    "DropdownMenuRadioItem",
    "DropdownMenuSeparator",
    "DropdownMenuShortcut",
    "DropdownMenuSub",
    "DropdownMenuSubContent",
    "DropdownMenuSubTrigger",
    "DropdownMenuTrigger",
    "Form",
    "FormControl",
    "FormDescription",
    "FormField",
    "FormItem",
    "FormLabel",
    "FormMessage",
    "HoverCard",
    "HoverCardContent",
    "HoverCardTrigger",
    "Input",
    "InputGroup",
    "InputGroupAddon",
    "InputGroupButton",
    "InputGroupInput",
    "InputGroupText",
    "InputGroupTextarea",
    "Label",
    "Pagination",
    "Popover",
    "PopoverAnchor",
    "PopoverContent",
    "PopoverTrigger",
    "Progress",
    "ResizableHandle",
    "ResizablePanel",
    "ResizablePanelGroup",
    "ScrollArea",
    "ScrollBar",
    "Select",
    "SelectContent",
    "SelectGroup",
    "SelectItem",
    "SelectLabel",
    "SelectScrollDownButton",
    "SelectScrollUpButton",
    "SelectSeparator",
    "SelectTrigger",
    "SelectValue",
    "Separator",
    "Sheet",
    "SheetClose",
    "SheetContent",
    "SheetDescription",
    "SheetFooter",
    "SheetHeader",
    "SheetTitle",
    "SheetTrigger",
    "Skeleton",
    "Slider",
    "StatusDot",
    "StatusIndicator",
    "Switch",
    "Table",
    "TableBody",
    "TableCaption",
    "TableCell",
    "TableFooter",
    "TableHead",
    "TableHeader",
    "TableRow",
    "Tabs",
    "TabsContent",
    "TabsList",
    "TabsTrigger",
    "Textarea",
    "ThemeToggle",
    "Tooltip",
    "TooltipContent",
    "TooltipProvider",
    "TooltipTrigger",
    "Tree",
    "TreeItem",
    "TreeItemContent",
    "TreeItemGroup",
    "XLDialog",
    "XLDialogClose",
    "XLDialogContent",
    "XLDialogHeader",
    "XLDialogTitle",
    "XLDialogTrigger",
    "badgeVariants",
    "buttonGroupVariants",
    "buttonVariants",
    "getConnectionStateLabel",
    "tabsListVariants",
    "useFormField",
    "useRovingListNavigation",
  ],
};

describe("barrel 导出契约", () => {
  for (const [group, names] of Object.entries(EXPECTED_EXPORTS)) {
    test(`${group} 分组的导出都能从 barrel 取到`, () => {
      for (const name of names) {
        expect(Object.hasOwn(barrel, name), `${group} 分组缺少导出：${name}`).toBe(true);
      }
    });
  }

  test("barrel 的运行时导出均非空", () => {
    for (const [name, value] of Object.entries(barrel)) {
      expect(value, `${name} 的导出值为 null`).not.toBeNull();
      expect(value, `${name} 的导出值为 undefined`).not.toBeUndefined();
      if (typeof value === "string") {
        expect(value.length, `${name} 的导出值为空字符串`).toBeGreaterThan(0);
      }
    }
  });

  test("barrel 的运行时导出总数与期望清单一致", () => {
    const expectedTotal = Object.values(EXPECTED_EXPORTS).reduce((sum, names) => sum + names.length, 0);
    expect(Object.keys(barrel).length, "导出数量已变化，请同步 EXPECTED_EXPORTS").toBe(expectedTotal);
  });
});
